// <auto-generated />
namespace week5Lec_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddingAuthorToBooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingAuthorToBooks));
        
        string IMigrationMetadata.Id
        {
            get { return "202308291434028_AddingAuthorToBooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
