// <auto-generated />
namespace FIT5032_MyCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialmodel1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialmodel1));
        
        string IMigrationMetadata.Id
        {
            get { return "202308201341269_initialmodel1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
